### ISSUE TITLE
How to run with GPU?

### ISSUE THREAD

**Issue by BoyuLyu** [Imbrosci/synaptic-vesicles-detection#7]
How to activate using GPU for the GUI? Is it started automatically?

**Comment by Imbrosci** [comment]
Yes, it should. In the classifiers scripts there is a line that allows PyTorch to check if your computer has a GPU and if it finds one it should use it.
If you want to check if PyTorch finds your GPU you can run the following line in python (after importing PyTorch of course):
torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
and see what it returns. As you can imagine, it should return cuda:0, if it returns cpu it means PyTorch did not find the GPU. 
PyTorch should also be install correctly to use it with GPU. Please follow the instruction at the following page: https://pytorch.org/.
There you should select the CUDA of your system and you will get the right command to use for the installation.
I hope this helps!

Best regards,
Barbara

**Comment by BoyuLyu** [comment]
Thanks! I checked, and PyTorch can find GPU. But still, it is running very slowly.
 I input one image with 2700x2100, which has been running for 1+hr. Not sure which part I did wrong.

**Comment by Imbrosci** [comment]
Did you make sure that you have calculated the pixel size correctly and that you have entered it in nanometer in the GUI? May I ask how big is your image in micrometer and / or which pixel size value did you enter (how big is each side of one pixel in nanometer)?
I am asking this because, the script does a rescaling of the images 'behind the scene' to then explore little overlapping windows of two specific sizes across the whole images. The size of these windows is good to fit a synaptic vesicle (a bit larger) or a few synaptic vesicles. A incorrect pixel size, if larger than it should, will cause an unnecessary upscaling of your image, which would results in a lot of additional time for analysis and in a poor performance. Just to give you an idea, a likely value for pixel size ranges from less than 1 nm to few nm. It cannot be much bigger than 10nm (10nm is already a lot), otherwise the magnification of your images would be too low to recognize synaptic vesicles at all (I guess you know this better than me).

Let me know if this helps and / or if you need further support!

Barbara

**Comment by BoyuLyu** [comment]
Thanks for the prompt reply. I am working on one Z-slice with 2700 x 2100 pixels. The resolution is 8 nm.

**Comment by Imbrosci** [comment]
It is a quite big image, it may indeed take sometimes. I hope you can see the synaptic vesicles clearly if you have such resolution. I am not sure how well will the performance of the model be on that resolution. Do you have higher resolution images? If you go below 5 nm would be better. Basically, as long as you can see the vesicles by eye as little circles with a hole inside (similar to a ring) the model should perform decently well. If you just see the synaptic vesicles as dots, the performance may drop a lot using the available trained model. Another point which may help to to speed up the analysis may be to answer no (typing: 'n') to the question if you want the algorithm to estimate the vesicles area (of course, if this is not relevant to you, but even if it is relevant, you can type 'n' once to see the difference in the time it takes for analyzing one image); indeed estimating the vesicles area takes a while too.

All the best,
Barbara

**Comment by BoyuLyu** [comment]
Oh, I see. Thanks a lot for the suggestion. To be honest, 8nm is indeed a bit of a stretch to clearly see the vesicles.

**Comment by Imbrosci** [comment]
You are welcome. Unfortunately, I assume that if you don't see the vesicles as 'ring'-like structures, the algorithm will not perform well. You can try anyway, but if you have higher resolution images, that you can use for your purposes, the performance will likely be much better.
Good luck!

Best wishes,
Barbara
